version: "3.4"
services:
  flask:
    build: ./flask
    working_dir: /usr/src/flask
    expose:
      - 5000
    ports:
      - "5000:5000"
    volumes:
      - ./flask:/usr/src/flask

  frontend:
    build: ./frontend
    working_dir: /usr/src/frontend
    expose:
      - 3000
    environment:
      HOST: 0.0.0.0
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/frontend
    links:
      - "flask:flask"
